services:
  - type: web
    name: grace-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
